export type ApplicantOption = Readonly<{
  value: string
  label: string
}>

function nationality(value: string, label: string): ApplicantOption {
  return { value: `NAT-${value}`, label }
}

// Current public e-Visa eligibility catalogue captured on 28 August 2026.
// The published page numbers 174 entries but lists Kenya twice; this catalogue
// intentionally contains the 173 unique eligible nationalities/regions.
export const EVISA_ELIGIBLE_NATIONALITIES = Object.freeze(([
  nationality('ALBANIA', 'Albania'),
  nationality('ANDORRA', 'Andorra'),
  nationality('ANGOLA', 'Angola'),
  nationality('ANGUILLA', 'Anguilla'),
  nationality('ANTIGUA-BARBUDA', 'Antigua and Barbuda'),
  nationality('ARGENTINA', 'Argentina'),
  nationality('ARMENIA', 'Armenia'),
  nationality('ARUBA', 'Aruba'),
  nationality('AUSTRALIA', 'Australia'),
  nationality('AUSTRIA', 'Austria'),
  nationality('AZERBAIJAN', 'Azerbaijan'),
  nationality('BAHAMAS', 'Bahamas'),
  nationality('BAHRAIN', 'Bahrain'),
  nationality('BANGLADESH', 'Bangladesh'),
  nationality('BARBADOS', 'Barbados'),
  nationality('BELARUS', 'Belarus'),
  nationality('BELGIUM', 'Belgium'),
  nationality('BELIZE', 'Belize'),
  nationality('BENIN', 'Benin'),
  nationality('BOLIVIA', 'Bolivia'),
  nationality('BOSNIA-HERZEGOVINA', 'Bosnia and Herzegovina'),
  nationality('BOTSWANA', 'Botswana'),
  nationality('BRAZIL', 'Brazil'),
  nationality('BRUNEI', 'Brunei'),
  nationality('BULGARIA', 'Bulgaria'),
  nationality('BURUNDI', 'Burundi'),
  nationality('CAMBODIA', 'Cambodia'),
  nationality('CAMEROON', 'Cameroon'),
  nationality('CANADA', 'Canada'),
  nationality('CAPE-VERDE', 'Cape Verde'),
  nationality('CAYMAN-ISLANDS', 'Cayman Islands'),
  nationality('CHILE', 'Chile'),
  nationality('COLOMBIA', 'Colombia'),
  nationality('COMOROS', 'Comoros'),
  nationality('COOK-ISLANDS', 'Cook Islands'),
  nationality('COSTA-RICA', 'Costa Rica'),
  nationality('COTE-DIVOIRE', 'Côte d’Ivoire'),
  nationality('CROATIA', 'Croatia'),
  nationality('CUBA', 'Cuba'),
  nationality('CYPRUS', 'Cyprus'),
  nationality('CZECH-REPUBLIC', 'Czech Republic'),
  nationality('DENMARK', 'Denmark'),
  nationality('DJIBOUTI', 'Djibouti'),
  nationality('DOMINICA', 'Dominica'),
  nationality('DOMINICAN-REPUBLIC', 'Dominican Republic'),
  nationality('ECUADOR', 'Ecuador'),
  nationality('EL-SALVADOR', 'El Salvador'),
  nationality('EQUATORIAL-GUINEA', 'Equatorial Guinea'),
  nationality('ERITREA', 'Eritrea'),
  nationality('ESTONIA', 'Estonia'),
  nationality('ESWATINI', 'Eswatini'),
  nationality('FIJI', 'Fiji'),
  nationality('FINLAND', 'Finland'),
  nationality('FRANCE', 'France'),
  nationality('GABON', 'Gabon'),
  nationality('GAMBIA', 'Gambia'),
  nationality('GEORGIA', 'Georgia'),
  nationality('GERMANY', 'Germany'),
  nationality('GHANA', 'Ghana'),
  nationality('GIBRALTAR', 'Gibraltar'),
  nationality('GREECE', 'Greece'),
  nationality('GRENADA', 'Grenada'),
  nationality('GUATEMALA', 'Guatemala'),
  nationality('GUERNSEY', 'Guernsey'),
  nationality('GUINEA', 'Guinea'),
  nationality('GUYANA', 'Guyana'),
  nationality('HAITI', 'Haiti'),
  nationality('HONDURAS', 'Honduras'),
  nationality('HUNGARY', 'Hungary'),
  nationality('ICELAND', 'Iceland'),
  nationality('INDONESIA', 'Indonesia'),
  nationality('IRELAND', 'Ireland'),
  nationality('ISLE-OF-MAN', 'Isle of Man'),
  nationality('ISRAEL', 'Israel'),
  nationality('ITALY', 'Italy'),
  nationality('JAMAICA', 'Jamaica'),
  nationality('JAPAN', 'Japan'),
  nationality('JERSEY', 'Jersey'),
  nationality('JORDAN', 'Jordan'),
  nationality('KAZAKHSTAN', 'Kazakhstan'),
  nationality('KENYA', 'Kenya'),
  nationality('KIRIBATI', 'Kiribati'),
  nationality('KUWAIT', 'Kuwait'),
  nationality('KYRGYZSTAN', 'Kyrgyzstan'),
  nationality('LAOS', 'Laos'),
  nationality('LATVIA', 'Latvia'),
  nationality('LESOTHO', 'Lesotho'),
  nationality('LIBERIA', 'Liberia'),
  nationality('LIECHTENSTEIN', 'Liechtenstein'),
  nationality('LITHUANIA', 'Lithuania'),
  nationality('LUXEMBOURG', 'Luxembourg'),
  nationality('NORTH-MACEDONIA', 'North Macedonia'),
  nationality('MADAGASCAR', 'Madagascar'),
  nationality('MALAWI', 'Malawi'),
  nationality('MALAYSIA', 'Malaysia'),
  nationality('MALI', 'Mali'),
  nationality('MALTA', 'Malta'),
  nationality('MARSHALL-ISLANDS', 'Marshall Islands'),
  nationality('MAURITANIA', 'Mauritania'),
  nationality('MAURITIUS', 'Mauritius'),
  nationality('MEXICO', 'Mexico'),
  nationality('MICRONESIA', 'Micronesia'),
  nationality('MOLDOVA', 'Moldova'),
  nationality('MONACO', 'Monaco'),
  nationality('MONGOLIA', 'Mongolia'),
  nationality('MONTENEGRO', 'Montenegro'),
  nationality('MONTSERRAT', 'Montserrat'),
  nationality('MOROCCO', 'Morocco'),
  nationality('MOZAMBIQUE', 'Mozambique'),
  nationality('MYANMAR', 'Myanmar'),
  nationality('NAMIBIA', 'Namibia'),
  nationality('NAURU', 'Nauru'),
  nationality('NETHERLANDS', 'Netherlands'),
  nationality('NEW-ZEALAND', 'New Zealand'),
  nationality('NICARAGUA', 'Nicaragua'),
  nationality('NIGER', 'Niger'),
  nationality('NIUE', 'Niue'),
  nationality('NORWAY', 'Norway'),
  nationality('OMAN', 'Oman'),
  nationality('PALAU', 'Palau'),
  nationality('PALESTINE', 'Palestine'),
  nationality('PANAMA', 'Panama'),
  nationality('PAPUA-NEW-GUINEA', 'Papua New Guinea'),
  nationality('PARAGUAY', 'Paraguay'),
  nationality('PERU', 'Peru'),
  nationality('PHILIPPINES', 'Philippines'),
  nationality('POLAND', 'Poland'),
  nationality('PORTUGAL', 'Portugal'),
  nationality('QATAR', 'Qatar'),
  nationality('REPUBLIC-OF-KOREA', 'Republic of Korea'),
  nationality('ROMANIA', 'Romania'),
  nationality('RUSSIA', 'Russia'),
  nationality('RWANDA', 'Rwanda'),
  nationality('SAINT-KITTS-NEVIS', 'Saint Kitts and Nevis'),
  nationality('SAINT-LUCIA', 'Saint Lucia'),
  nationality('SAINT-VINCENT-GRENADINES', 'Saint Vincent and the Grenadines'),
  nationality('SAMOA', 'Samoa'),
  nationality('SAN-MARINO', 'San Marino'),
  nationality('SENEGAL', 'Senegal'),
  nationality('SERBIA', 'Serbia'),
  nationality('SEYCHELLES', 'Seychelles'),
  nationality('SIERRA-LEONE', 'Sierra Leone'),
  nationality('SINGAPORE', 'Singapore'),
  nationality('SLOVAKIA', 'Slovakia'),
  nationality('SLOVENIA', 'Slovenia'),
  nationality('SOLOMON-ISLANDS', 'Solomon Islands'),
  nationality('SOUTH-AFRICA', 'South Africa'),
  nationality('SPAIN', 'Spain'),
  nationality('SRI-LANKA', 'Sri Lanka'),
  nationality('SURINAME', 'Suriname'),
  nationality('SWEDEN', 'Sweden'),
  nationality('SWITZERLAND', 'Switzerland'),
  nationality('TAIWAN', 'Taiwan'),
  nationality('TAJIKISTAN', 'Tajikistan'),
  nationality('TANZANIA', 'Tanzania'),
  nationality('THAILAND', 'Thailand'),
  nationality('TOGO', 'Togo'),
  nationality('TONGA', 'Tonga'),
  nationality('TRINIDAD-TOBAGO', 'Trinidad and Tobago'),
  nationality('TURKS-CAICOS', 'Turks and Caicos Islands'),
  nationality('TUVALU', 'Tuvalu'),
  nationality('UNITED-ARAB-EMIRATES', 'United Arab Emirates'),
  nationality('UNITED-KINGDOM', 'United Kingdom'),
  nationality('UNITED-STATES', 'United States of America'),
  nationality('UKRAINE', 'Ukraine'),
  nationality('URUGUAY', 'Uruguay'),
  nationality('UZBEKISTAN', 'Uzbekistan'),
  nationality('VANUATU', 'Vanuatu'),
  nationality('VATICAN-CITY', 'Vatican City (Holy See)'),
  nationality('VENEZUELA', 'Venezuela'),
  nationality('VIETNAM', 'Vietnam'),
  nationality('ZAMBIA', 'Zambia'),
  nationality('ZIMBABWE', 'Zimbabwe'),
] satisfies ApplicantOption[])
  .sort((left, right) => left.label.localeCompare(right.label, 'en'))
  .map((option) => Object.freeze(option)))

export const NATIONALITY_NOT_LISTED = Object.freeze({
  value: 'NAT-NOT-LISTED',
  label: 'My nationality/region is not listed',
} satisfies ApplicantOption)

export const PASSPORT_TYPES = Object.freeze([
  { value: 'PASSPORT-ORDINARY', label: 'Ordinary Passport' },
  { value: 'PASSPORT-OFFICIAL', label: 'Official Passport' },
  { value: 'PASSPORT-DIPLOMATIC', label: 'Diplomatic Passport' },
  { value: 'PASSPORT-SERVICE', label: 'Service Passport' },
  { value: 'PASSPORT-SPECIAL', label: 'Special Passport' },
] satisfies readonly ApplicantOption[])

export const APPLICANT_OPTION_LABELS: Readonly<Record<string, string>> = Object.freeze(
  Object.fromEntries(
    [...EVISA_ELIGIBLE_NATIONALITIES, NATIONALITY_NOT_LISTED, ...PASSPORT_TYPES].map(
      ({ value, label }) => [value, label],
    ),
  ),
)

export const EVISA_ELIGIBLE_NATIONALITY_VALUES = Object.freeze(
  EVISA_ELIGIBLE_NATIONALITIES.map(({ value }) => value),
)

export const PASSPORT_TYPE_VALUES = Object.freeze(PASSPORT_TYPES.map(({ value }) => value))
